template:
  path: beanstalk.yaml
stack_name: agora-prod
dependencies:
  - common/agora-common.yaml
  - common/agora-dns.yaml
  - prod/agora-docdb.yaml
parameters:
  AppDeployBucket: 'org-sagebase-agora-deployment-agora-prod'
  AppEnv: 'prod'
  AppHealthcheckUrl: '/about'
  AutoScalingMaxSize: '6'
  AutoScalingMinSize: '3'
  EbHealthReportingSystem: 'enhanced'
  EbDeploymentPolicy: 'RollingWithAdditionalBatch'
  SnsBounceNotificationEndpoint: 'agora-prod-bounce-notifications@sagebase.org'
  SnsNotificationEndpoint: 'agora-prod@sagebase.org'
  EbSolutionStackName: '64bit Amazon Linux 2 v5.5.0 running Node.js 12'
  EC2InstanceType: 't3.large'
  EC2KeyName: 'agora-access'
  MongodbHost: !stack_output_external agora-docdb-prod::ClusterEndpoint
  MongodbAccessSecurityGroup: !stack_output_external agora-docdb-prod::DocumentDbAccessSecurityGroup
  VpcName: 'agoravpc'
  CertificateArn: !stack_output_external agora-dns::SSLCertificate
