template:
  path: documentdb.yaml
stack_name: agora-docdb-develop
stack_tags:
  Environment: "develop"
dependencies:
  - develop/agoravpc.yaml
parameters:
  VpcName: "agoravpc"
  MasterUser: "master"
  MasterPassword: !ssm /agora-develop/MongodbPassword
  DBInstanceClass: "db.r5.large"
